
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwhhliwmyecyrtcpkkxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aGhsaXdteWVjeXJ0Y3Bra3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTg3OTIsImV4cCI6MjA1ODI5NDc5Mn0.hYs4SCryIePzbeGR6ezHCT1Qi7x69prBNgGqihWP47U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Since the database tables don't match what we're trying to access,
// we'll use type assertions to work around the type issues
export const fromSupabase = {
  // We'll use any type to bypass type checking since these tables don't exist yet
  books: () => supabase.from('books' as any),
  categories: () => supabase.from('categories' as any),
  book_categories: () => supabase.from('book_categories' as any),
  bundles: () => supabase.from('bundles' as any),
  bundle_books: () => supabase.from('bundle_books' as any),
  favorites: () => supabase.from('favorites'),
  mailing_list: () => supabase.from('mailing_list' as any)
};
