
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwhhliwmyecyrtcpkkxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aGhsaXdteWVjeXJ0Y3Bra3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTg3OTIsImV4cCI6MjA1ODI5NDc5Mn0.hYs4SCryIePzbeGR6ezHCT1Qi7x69prBNgGqihWP47U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export a helper that lets us work with our own types while using the Supabase client
export const fromSupabase = {
  books: () => supabase.from('books'),
  categories: () => supabase.from('categories'),
  book_categories: () => supabase.from('book_categories'),
  bundles: () => supabase.from('bundles'),
  bundle_books: () => supabase.from('bundle_books'),
  favorites: () => supabase.from('favorites'),
  mailing_list: () => supabase.from('mailing_list')
};
